### ISSUE TITLE
Can you provide me with the files so that I can translate this mod? 

### ISSUE THREAD

**Issue by thefish12357** [DoubleMa/DoubleQoLMod#1]
Hi~
I would like to try to translate this mod into Chinese to make it easier for me to play the game, can you provide me with a text configuration file?
I will return the translated text to you!

**Comment by DoubleMa** [comment]
Hey,

Thanks for reaching out! Right now, the mod doesn't have a built-in translator. But I'll definitely look into adding one in a future update. If you have any other ideas or questions, feel free to shoot them my way!

Cheers

**Comment by DoubleMa** [comment]
Added in version 1.6.0. Please check discord on how you can use it.
